default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: coffee_app_development

test:
  <<: *default
  database: coffee_app_test

production:
  <<: *default
  database: coffee_records_production
  username: coffee_records
  url: <%= ENV['DATABASE_URL'] %>