name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Set up database
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/coffee_records_test
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/coffee_records_test
        RAILS_ENV: test
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop --parallel

    - name: Check for security vulnerabilities
      run: bundle exec bundle audit check --update